# Generated by Django 6.0.7 on 2026-07-13 03:26

import django.db.models.deletion
import django.utils.timezone
import gemba.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='pregunta')),
                ('criterio', models.TextField(help_text='Contexto que explica al operador qué se evalúa en esta pregunta.', verbose_name='criterio')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gemba.area', verbose_name='área')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['area__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('status', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('COMPLETA', 'Completa')], default='EN_PROGRESO', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completada')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walks', to='gemba.area', verbose_name='área')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walks', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
            ],
            options={
                'verbose_name': 'caminata',
                'verbose_name_plural': 'caminatas',
                'ordering': ['-date', 'area__order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No conforme'), ('PARCIAL', 'Parcial')], max_length=20, verbose_name='respuesta')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=gemba.models.answer_photo_path, verbose_name='fotografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='gemba.question', verbose_name='pregunta')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gemba.walk', verbose_name='caminata')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='walk',
            constraint=models.UniqueConstraint(fields=('area', 'date'), name='una_caminata_por_area_dia'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('walk', 'question'), name='una_respuesta_por_pregunta'),
        ),
    ]
